services:
#    simplylink_auth_sdk.example:
#        class: Simplylink\AuthSDKBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    simplylink.oauth.client:
            class: Simplylink\AuthSDKBundle\Utils\SLoAuthClient
            arguments: ["%client_id","%client_secret","%return_uri"]


    simplylink.oauth.sdk:
            class: Simplylink\AuthSDKBundle\Utils\SLoAuthConnector
            arguments: ["@simplylink.oauth.client"]



    simplylink.serilizer.handler.currency:
        class:     Simplylink\AuthSDKBundle\Handlers\CurrencySerializer
        tags:
            - { name: jms_serializer.subscribing_handler }


    simplylink.serilizer.handler.country:
            class:     Simplylink\AuthSDKBundle\Handlers\CountrySerializer
            tags:
                - { name: jms_serializer.subscribing_handler }

    simplylink.serilizer.handler.payment_gateway:
        class:     Simplylink\AuthSDKBundle\Handlers\PaymentGatewaySerializer
        tags:
            - { name: jms_serializer.subscribing_handler }


    simplylink.serilizer.handler.application_plan:
        class:     Simplylink\AuthSDKBundle\Handlers\ApplicationPlanSerializer
        tags:
            - { name: jms_serializer.subscribing_handler }

    simplylink.serilizer.handler.datetime:
        class:     Simplylink\AuthSDKBundle\Handlers\DatetimeSerializer
        tags:
            - { name: jms_serializer.subscribing_handler }


    simplylink.serilizer.handler.organization_role:
        class:     Simplylink\AuthSDKBundle\Handlers\OrganizationRolesSerializer
        tags:
            - { name: jms_serializer.subscribing_handler }



